stages:
  - build
  - deploy
  - undeploy

build:
  stage: build
  tags:
    - shell-docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
deploy:
  stage: deploy
  tags:
    - shell-kubectl-xand00
  when: manual
  before_script:
    - kubectl config use-context vehicle-services/backend/vehicle-services-backend-strapi:shipovka-gitlab-agent
    - kubectl delete secret regcred || true
    - kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USER --docker-password=$READ_REGISTRY_TOKEN
  script:
    - helm upgrade
      --install
      --set container.image=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      --set replicaCount=3
      --set PORT=1337
      --set NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
      $CI_PROJECT_NAME
      .
undeploy:
  stage: undeploy
  tags:
    - shell-kubectl-xand00
  when: manual
  before_script:
    - kubectl config use-context vehicle-services/backend/vehicle-services-backend-strapi:shipovka-gitlab-agent
  script:
    - helm uninstall $CI_PROJECT_NAME