image: docker:20.10.14-alpine3.15

stages:
  - build
  - deploy

services:
 - docker:20.10.14-dind-alpine3.15

build:
  stage: build
  tags:
    - gitlab-docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build
      --build-arg NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  tags:
    - vehicle-services-prod-shell
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker container rm $CI_PROJECT_NAME -f
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_PROJECT_NAME
    - docker run --name $CI_PROJECT_NAME -d -p 80:3000 $CI_PROJECT_NAME
  rules:
    - when: manual

# stages:
#   - hello_world

# hello_world:
#   stage: hello_world
#   tags:
#     - gitlab-docker
#   script:
#     - cat Dockerfile
#     - echo 'hello world'