version: "3.9"
services:
  frontend:
    build:
      context: .
      target: deps
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn dev